services:
  - type: worker
    name: enderland-discord-bot
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_KEYS
        sync: false
